"""Report rendering (Section 21.10).

Rules this module obeys:
  * no profitability claim is printed by default - measured values and
    assumptions only, and no adjectives
  * the cost model, risk config version, data hash and code version appear on
    every report, so a screenshot is still traceable
  * baselines are printed alongside the candidate, never separately
  * a synthetic dataset gets a loud banner
"""
from __future__ import annotations

from typing import Any, Mapping, Sequence

from maysani_quant.backtest.engine import BacktestResult
from maysani_quant.backtest.metrics import MetricsBundle

SYNTHETIC_BANNER = """
!!! ====================================================================== !!!
!!!  SYNTHETIC DATASET - NOT MARKET DATA                                   !!!
!!!  These bars were generated by a deterministic process for pipeline      !!!
!!!  testing. Any number below describes the generator, not EUR/USD.        !!!
!!! ====================================================================== !!!
""".strip()

NO_CLAIM_FOOTER = """
This report measures a historical simulation under the stated assumptions.
It is not evidence of profitability and is not an authorisation to trade
real capital. Promotion requires walk-forward validation, untouched holdout
evaluation, cost/stress scenarios, paper trading and shadow-broker testing
(Section 13.8).
""".strip()


def _fmt(value: Any) -> str:
    if isinstance(value, float):
        if value != value:  # NaN
            return "nan"
        if abs(value) >= 1000 or (abs(value) < 0.0001 and value != 0):
            return f"{value:.6g}"
        return f"{value:,.6f}".rstrip("0").rstrip(".")
    return str(value)


def _table(rows: Sequence[tuple[str, Any]], width: int = 38) -> str:
    return "\n".join(f"  {label:<{width}} {_fmt(value)}" for label, value in rows)


def render_run_report(
    result: BacktestResult,
    metrics: MetricsBundle,
    cost_model: Mapping[str, Any],
    risk_config_version: str,
    code_version: str,
    dataset_path: str,
    timeframe: str,
    trial_count: int,
) -> str:
    lines: list[str] = []
    if result.dataset_is_synthetic:
        lines += [SYNTHETIC_BANNER, ""]

    lines += [
        "=" * 74,
        f"MAYSANI QUANT V0.1 - BACKTEST REPORT",
        "=" * 74,
        "",
        "PROVENANCE",
        _table(
            [
                ("run_id", result.run_id),
                ("experiment_id", result.experiment_id),
                ("strategy", f"{result.strategy_id}@{result.strategy_version}"),
                ("code_version", code_version),
                ("risk_config_version", risk_config_version),
                ("config_hash", result.config_hash[:16]),
                ("data_hash", result.data_hash[:16]),
                ("dataset", dataset_path),
                ("timeframe", timeframe),
                ("bars_processed", result.bars_processed),
                ("warmup_bars", result.warmup_bars),
                ("journal_fingerprint", result.journal_fingerprint[:16]),
                ("experiment_trials_recorded", trial_count),
            ]
        ),
        "",
        "COST MODEL ASSUMPTIONS (configured, not observed)",
        _table([(k, v) for k, v in cost_model.items()]),
        "",
    ]

    if result.validation is not None:
        lines += ["DATA VALIDATION", f"  {result.validation.summary()}", ""]

    m = metrics.values
    lines += [
        "RESULT",
        _table(
            [
                ("initial_equity", m.get("initial_equity")),
                ("final_equity", m.get("final_equity")),
                ("gross_return", m.get("gross_return")),
                ("net_return", m.get("total_return")),
                ("log_growth", m.get("log_growth")),
                ("organism_state", m.get("final_state")),
            ]
        ),
        "",
        "COSTS",
        _table(
            [
                ("total_costs", m.get("total_costs")),
                ("spread_and_slippage", m.get("spread_slippage_costs")),
                ("commissions", m.get("commissions")),
                ("financing", m.get("financing_costs")),
                ("cost_drag_pct_of_initial", m.get("cost_drag_pct_of_initial")),
            ]
        ),
        "",
        "RISK / PATH",
        _table(
            [
                ("max_drawdown", m.get("max_drawdown")),
                ("max_drawdown_duration_bars", m.get("max_drawdown_duration_bars")),
                ("expected_shortfall_5pct", m.get("expected_shortfall_5pct")),
                ("max_leverage_used", m.get("max_leverage_used")),
                ("max_margin_used", m.get("max_margin_used")),
            ]
        ),
        "",
        "ACTIVITY",
        _table(
            [
                ("trade_count", m.get("trade_count")),
                ("hit_rate", m.get("hit_rate")),
                ("payoff_ratio", m.get("payoff_ratio")),
                ("time_in_market_pct", m.get("time_in_market_pct")),
                ("turnover_notional", m.get("turnover_notional")),
            ]
        ),
        "",
        "RISK VETOES (entries refused, by reason)",
        _table(
            sorted(
                ((k, v) for k, v in (m.get("risk_vetoes") or {}).items()),
                key=lambda kv: -kv[1],
            )
            or [("none", 0)]
        ),
        "",
        "RATIOS (see disclosures)",
        _table(
            [
                ("sharpe", m.get("sharpe")),
                ("sortino", m.get("sortino")),
                ("calmar", m.get("calmar")),
            ]
        ),
        "",
        "DISCLOSURES",
        _table([(k, v) for k, v in metrics.disclosures.items()], width=32),
        "",
    ]
    return "\n".join(lines)


def render_comparison(
    rows: Sequence[tuple[str, MetricsBundle]], include_footer: bool = True
) -> str:
    """Baseline table. no_trade_v1 is always printed first if present."""
    header = (
        f"  {'strategy':<22}{'net_ret':>11}{'gross_ret':>11}{'max_dd':>9}"
        f"{'sharpe':>9}{'trades':>8}{'costs':>10}{'state':>7}"
    )
    lines = ["=" * 74, "BASELINE COMPARISON (same data, same costs, same risk config)", "=" * 74, header, "  " + "-" * 70]

    def sort_key(item: tuple[str, MetricsBundle]) -> tuple[int, str]:
        order = {"no_trade_v1": 0, "buy_and_hold_v1": 1}
        return (order.get(item[0], 2), item[0])

    for name, bundle in sorted(rows, key=sort_key):
        m = bundle.values
        lines.append(
            f"  {name:<22}"
            f"{m.get('total_return', 0.0):>11.4f}"
            f"{m.get('gross_return', 0.0):>11.4f}"
            f"{m.get('max_drawdown', 0.0):>9.4f}"
            f"{m.get('sharpe', 0.0):>9.3f}"
            f"{m.get('trade_count', 0):>8}"
            f"{m.get('total_costs', 0.0):>10.4f}"
            f"{str(m.get('final_state', '')):>7}"
        )
    lines.append("")

    # A strategy that never traded is only a valid result if it is MEANT to be
    # flat. Anything else is a silently inert control, and must be said aloud.
    inert = [
        (name, b) for name, b in rows
        if b.values.get("trade_count", 0) == 0 and name != "no_trade_v1"
    ]
    if inert:
        lines.append("  WARNING - strategies that never traded:")
        for name, b in inert:
            vetoes = b.values.get("risk_vetoes") or {}
            top = max(vetoes.items(), key=lambda kv: kv[1]) if vetoes else None
            why = f"top veto {top[0]} x{top[1]}" if top else "no entry signal was ever emitted"
            lines.append(f"    {name}: {why}")
        lines.append("")

    if include_footer:
        lines += [NO_CLAIM_FOOTER, ""]
    return "\n".join(lines)
